/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminWarehousesRouteImport } from './routes/admin/warehouses'
import { Route as AdminTrackingPresetsRouteImport } from './routes/admin/tracking-presets'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminRoutesRouteImport } from './routes/admin/routes'
import { Route as AdminOversizeRulesRouteImport } from './routes/admin/oversize-rules'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminMeasureRouteImport } from './routes/admin/measure'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminIntakeScanRouteImport } from './routes/admin/intake-scan'
import { Route as AdminHsCodesRouteImport } from './routes/admin/hs-codes'
import { Route as AdminHistoryRouteImport } from './routes/admin/history'
import { Route as AdminForbiddenRouteImport } from './routes/admin/forbidden'
import { Route as AdminDetainedRouteImport } from './routes/admin/detained'
import { Route as AdminDestinationsRouteImport } from './routes/admin/destinations'
import { Route as AdminCargoTypesRouteImport } from './routes/admin/cargo-types'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AdminWaybillsIndexRouteImport } from './routes/admin/waybills.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users.index'
import { Route as AdminShopIndexRouteImport } from './routes/admin/shop.index'
import { Route as AdminReceivingsIndexRouteImport } from './routes/admin/receivings.index'
import { Route as AdminPalletsIndexRouteImport } from './routes/admin/pallets.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders.index'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin/invoices.index'
import { Route as AdminForwardingsIndexRouteImport } from './routes/admin/forwardings.index'
import { Route as AdminDeliveryQueueIndexRouteImport } from './routes/admin/delivery-queue.index'
import { Route as AdminCartonsIndexRouteImport } from './routes/admin/cartons.index'
import { Route as AdminBatchesIndexRouteImport } from './routes/admin/batches.index'
import { Route as AuthenticatedForwardingIndexRouteImport } from './routes/_authenticated/forwarding.index'
import { Route as AdminWaybillsWaybillIdRouteImport } from './routes/admin/waybills.$waybillId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminShopInventoryRouteImport } from './routes/admin/shop.inventory'
import { Route as AdminShopCouponsRouteImport } from './routes/admin/shop.coupons'
import { Route as AdminShopCategoriesRouteImport } from './routes/admin/shop.categories'
import { Route as AdminShopBannersRouteImport } from './routes/admin/shop.banners'
import { Route as AdminShopArticlesRouteImport } from './routes/admin/shop.articles'
import { Route as AdminReceivingsReceivingIdRouteImport } from './routes/admin/receivings.$receivingId'
import { Route as AdminPalletsPalletIdRouteImport } from './routes/admin/pallets.$palletId'
import { Route as AdminOrdersProcurementRouteImport } from './routes/admin/orders.procurement'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders.$orderId'
import { Route as AdminInvoicesInvoiceIdRouteImport } from './routes/admin/invoices.$invoiceId'
import { Route as AdminForwardingsForwardingIdRouteImport } from './routes/admin/forwardings.$forwardingId'
import { Route as AdminDeliveryQueueCustomerKeyRouteImport } from './routes/admin/delivery-queue.$customerKey'
import { Route as AdminCartonsCartonIdRouteImport } from './routes/admin/cartons.$cartonId'
import { Route as AdminBatchesBatchIdRouteImport } from './routes/admin/batches.$batchId'
import { Route as AuthenticatedPayOrderIdRouteImport } from './routes/_authenticated/pay.$orderId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedForwardingForwardingIdRouteImport } from './routes/_authenticated/forwarding.$forwardingId'
import { Route as AdminShopProductsIndexRouteImport } from './routes/admin/shop.products.index'
import { Route as AdminShopOrdersIndexRouteImport } from './routes/admin/shop.orders.index'
import { Route as ApiPublicWechatCallbackRouteImport } from './routes/api/public/wechat.callback'
import { Route as ApiPublicHooksMarkOverdueRouteImport } from './routes/api/public/hooks/mark-overdue'
import { Route as AdminShopProductsProductIdRouteImport } from './routes/admin/shop.products.$productId'
import { Route as AdminShopOrdersProcurementRouteImport } from './routes/admin/shop.orders.procurement'
import { Route as AdminShopOrdersOrderIdRouteImport } from './routes/admin/shop.orders.$orderId'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminWarehousesRoute = AdminWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTrackingPresetsRoute = AdminTrackingPresetsRouteImport.update({
  id: '/tracking-presets',
  path: '/tracking-presets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOversizeRulesRoute = AdminOversizeRulesRouteImport.update({
  id: '/oversize-rules',
  path: '/oversize-rules',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMeasureRoute = AdminMeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntakeScanRoute = AdminIntakeScanRouteImport.update({
  id: '/intake-scan',
  path: '/intake-scan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHsCodesRoute = AdminHsCodesRouteImport.update({
  id: '/hs-codes',
  path: '/hs-codes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForbiddenRoute = AdminForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDetainedRoute = AdminDetainedRouteImport.update({
  id: '/detained',
  path: '/detained',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCargoTypesRoute = AdminCargoTypesRouteImport.update({
  id: '/cargo-types',
  path: '/cargo-types',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminWaybillsIndexRoute = AdminWaybillsIndexRouteImport.update({
  id: '/waybills/',
  path: '/waybills/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopIndexRoute = AdminShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReceivingsIndexRoute = AdminReceivingsIndexRouteImport.update({
  id: '/receivings/',
  path: '/receivings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPalletsIndexRoute = AdminPalletsIndexRouteImport.update({
  id: '/pallets/',
  path: '/pallets/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForwardingsIndexRoute = AdminForwardingsIndexRouteImport.update({
  id: '/forwardings/',
  path: '/forwardings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDeliveryQueueIndexRoute = AdminDeliveryQueueIndexRouteImport.update({
  id: '/delivery-queue/',
  path: '/delivery-queue/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCartonsIndexRoute = AdminCartonsIndexRouteImport.update({
  id: '/cartons/',
  path: '/cartons/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBatchesIndexRoute = AdminBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedForwardingIndexRoute =
  AuthenticatedForwardingIndexRouteImport.update({
    id: '/forwarding/',
    path: '/forwarding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminWaybillsWaybillIdRoute = AdminWaybillsWaybillIdRouteImport.update({
  id: '/waybills/$waybillId',
  path: '/waybills/$waybillId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopInventoryRoute = AdminShopInventoryRouteImport.update({
  id: '/shop/inventory',
  path: '/shop/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopCouponsRoute = AdminShopCouponsRouteImport.update({
  id: '/shop/coupons',
  path: '/shop/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopCategoriesRoute = AdminShopCategoriesRouteImport.update({
  id: '/shop/categories',
  path: '/shop/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopBannersRoute = AdminShopBannersRouteImport.update({
  id: '/shop/banners',
  path: '/shop/banners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopArticlesRoute = AdminShopArticlesRouteImport.update({
  id: '/shop/articles',
  path: '/shop/articles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReceivingsReceivingIdRoute =
  AdminReceivingsReceivingIdRouteImport.update({
    id: '/receivings/$receivingId',
    path: '/receivings/$receivingId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPalletsPalletIdRoute = AdminPalletsPalletIdRouteImport.update({
  id: '/pallets/$palletId',
  path: '/pallets/$palletId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersProcurementRoute = AdminOrdersProcurementRouteImport.update({
  id: '/orders/procurement',
  path: '/orders/procurement',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesInvoiceIdRoute = AdminInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForwardingsForwardingIdRoute =
  AdminForwardingsForwardingIdRouteImport.update({
    id: '/forwardings/$forwardingId',
    path: '/forwardings/$forwardingId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDeliveryQueueCustomerKeyRoute =
  AdminDeliveryQueueCustomerKeyRouteImport.update({
    id: '/delivery-queue/$customerKey',
    path: '/delivery-queue/$customerKey',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCartonsCartonIdRoute = AdminCartonsCartonIdRouteImport.update({
  id: '/cartons/$cartonId',
  path: '/cartons/$cartonId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBatchesBatchIdRoute = AdminBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedPayOrderIdRoute = AuthenticatedPayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForwardingForwardingIdRoute =
  AuthenticatedForwardingForwardingIdRouteImport.update({
    id: '/forwarding/$forwardingId',
    path: '/forwarding/$forwardingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminShopProductsIndexRoute = AdminShopProductsIndexRouteImport.update({
  id: '/shop/products/',
  path: '/shop/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopOrdersIndexRoute = AdminShopOrdersIndexRouteImport.update({
  id: '/shop/orders/',
  path: '/shop/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicWechatCallbackRoute = ApiPublicWechatCallbackRouteImport.update({
  id: '/api/public/wechat/callback',
  path: '/api/public/wechat/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMarkOverdueRoute =
  ApiPublicHooksMarkOverdueRouteImport.update({
    id: '/api/public/hooks/mark-overdue',
    path: '/api/public/hooks/mark-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminShopProductsProductIdRoute =
  AdminShopProductsProductIdRouteImport.update({
    id: '/shop/products/$productId',
    path: '/shop/products/$productId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminShopOrdersProcurementRoute =
  AdminShopOrdersProcurementRouteImport.update({
    id: '/shop/orders/procurement',
    path: '/shop/orders/procurement',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminShopOrdersOrderIdRoute = AdminShopOrdersOrderIdRouteImport.update({
  id: '/shop/orders/$orderId',
  path: '/shop/orders/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/admin/cargo-types': typeof AdminCargoTypesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/detained': typeof AdminDetainedRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/hs-codes': typeof AdminHsCodesRoute
  '/admin/intake-scan': typeof AdminIntakeScanRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/measure': typeof AdminMeasureRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/oversize-rules': typeof AdminOversizeRulesRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tracking-presets': typeof AdminTrackingPresetsRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/forwarding/$forwardingId': typeof AuthenticatedForwardingForwardingIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/pay/$orderId': typeof AuthenticatedPayOrderIdRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/admin/cartons/$cartonId': typeof AdminCartonsCartonIdRoute
  '/admin/delivery-queue/$customerKey': typeof AdminDeliveryQueueCustomerKeyRoute
  '/admin/forwardings/$forwardingId': typeof AdminForwardingsForwardingIdRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/procurement': typeof AdminOrdersProcurementRoute
  '/admin/pallets/$palletId': typeof AdminPalletsPalletIdRoute
  '/admin/receivings/$receivingId': typeof AdminReceivingsReceivingIdRoute
  '/admin/shop/articles': typeof AdminShopArticlesRoute
  '/admin/shop/banners': typeof AdminShopBannersRoute
  '/admin/shop/categories': typeof AdminShopCategoriesRoute
  '/admin/shop/coupons': typeof AdminShopCouponsRoute
  '/admin/shop/inventory': typeof AdminShopInventoryRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/waybills/$waybillId': typeof AdminWaybillsWaybillIdRoute
  '/forwarding/': typeof AuthenticatedForwardingIndexRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/cartons/': typeof AdminCartonsIndexRoute
  '/admin/delivery-queue/': typeof AdminDeliveryQueueIndexRoute
  '/admin/forwardings/': typeof AdminForwardingsIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pallets/': typeof AdminPalletsIndexRoute
  '/admin/receivings/': typeof AdminReceivingsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/waybills/': typeof AdminWaybillsIndexRoute
  '/admin/shop/orders/$orderId': typeof AdminShopOrdersOrderIdRoute
  '/admin/shop/orders/procurement': typeof AdminShopOrdersProcurementRoute
  '/admin/shop/products/$productId': typeof AdminShopProductsProductIdRoute
  '/api/public/hooks/mark-overdue': typeof ApiPublicHooksMarkOverdueRoute
  '/api/public/wechat/callback': typeof ApiPublicWechatCallbackRoute
  '/admin/shop/orders/': typeof AdminShopOrdersIndexRoute
  '/admin/shop/products/': typeof AdminShopProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/admin/cargo-types': typeof AdminCargoTypesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/detained': typeof AdminDetainedRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/hs-codes': typeof AdminHsCodesRoute
  '/admin/intake-scan': typeof AdminIntakeScanRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/measure': typeof AdminMeasureRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/oversize-rules': typeof AdminOversizeRulesRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tracking-presets': typeof AdminTrackingPresetsRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/forwarding/$forwardingId': typeof AuthenticatedForwardingForwardingIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/pay/$orderId': typeof AuthenticatedPayOrderIdRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/admin/cartons/$cartonId': typeof AdminCartonsCartonIdRoute
  '/admin/delivery-queue/$customerKey': typeof AdminDeliveryQueueCustomerKeyRoute
  '/admin/forwardings/$forwardingId': typeof AdminForwardingsForwardingIdRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/procurement': typeof AdminOrdersProcurementRoute
  '/admin/pallets/$palletId': typeof AdminPalletsPalletIdRoute
  '/admin/receivings/$receivingId': typeof AdminReceivingsReceivingIdRoute
  '/admin/shop/articles': typeof AdminShopArticlesRoute
  '/admin/shop/banners': typeof AdminShopBannersRoute
  '/admin/shop/categories': typeof AdminShopCategoriesRoute
  '/admin/shop/coupons': typeof AdminShopCouponsRoute
  '/admin/shop/inventory': typeof AdminShopInventoryRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/waybills/$waybillId': typeof AdminWaybillsWaybillIdRoute
  '/forwarding': typeof AuthenticatedForwardingIndexRoute
  '/admin/batches': typeof AdminBatchesIndexRoute
  '/admin/cartons': typeof AdminCartonsIndexRoute
  '/admin/delivery-queue': typeof AdminDeliveryQueueIndexRoute
  '/admin/forwardings': typeof AdminForwardingsIndexRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pallets': typeof AdminPalletsIndexRoute
  '/admin/receivings': typeof AdminReceivingsIndexRoute
  '/admin/shop': typeof AdminShopIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/waybills': typeof AdminWaybillsIndexRoute
  '/admin/shop/orders/$orderId': typeof AdminShopOrdersOrderIdRoute
  '/admin/shop/orders/procurement': typeof AdminShopOrdersProcurementRoute
  '/admin/shop/products/$productId': typeof AdminShopProductsProductIdRoute
  '/api/public/hooks/mark-overdue': typeof ApiPublicHooksMarkOverdueRoute
  '/api/public/wechat/callback': typeof ApiPublicWechatCallbackRoute
  '/admin/shop/orders': typeof AdminShopOrdersIndexRoute
  '/admin/shop/products': typeof AdminShopProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/admin/cargo-types': typeof AdminCargoTypesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/detained': typeof AdminDetainedRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/hs-codes': typeof AdminHsCodesRoute
  '/admin/intake-scan': typeof AdminIntakeScanRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/measure': typeof AdminMeasureRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/oversize-rules': typeof AdminOversizeRulesRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tracking-presets': typeof AdminTrackingPresetsRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/forwarding/$forwardingId': typeof AuthenticatedForwardingForwardingIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/pay/$orderId': typeof AuthenticatedPayOrderIdRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/admin/cartons/$cartonId': typeof AdminCartonsCartonIdRoute
  '/admin/delivery-queue/$customerKey': typeof AdminDeliveryQueueCustomerKeyRoute
  '/admin/forwardings/$forwardingId': typeof AdminForwardingsForwardingIdRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/procurement': typeof AdminOrdersProcurementRoute
  '/admin/pallets/$palletId': typeof AdminPalletsPalletIdRoute
  '/admin/receivings/$receivingId': typeof AdminReceivingsReceivingIdRoute
  '/admin/shop/articles': typeof AdminShopArticlesRoute
  '/admin/shop/banners': typeof AdminShopBannersRoute
  '/admin/shop/categories': typeof AdminShopCategoriesRoute
  '/admin/shop/coupons': typeof AdminShopCouponsRoute
  '/admin/shop/inventory': typeof AdminShopInventoryRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/waybills/$waybillId': typeof AdminWaybillsWaybillIdRoute
  '/_authenticated/forwarding/': typeof AuthenticatedForwardingIndexRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/cartons/': typeof AdminCartonsIndexRoute
  '/admin/delivery-queue/': typeof AdminDeliveryQueueIndexRoute
  '/admin/forwardings/': typeof AdminForwardingsIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pallets/': typeof AdminPalletsIndexRoute
  '/admin/receivings/': typeof AdminReceivingsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/waybills/': typeof AdminWaybillsIndexRoute
  '/admin/shop/orders/$orderId': typeof AdminShopOrdersOrderIdRoute
  '/admin/shop/orders/procurement': typeof AdminShopOrdersProcurementRoute
  '/admin/shop/products/$productId': typeof AdminShopProductsProductIdRoute
  '/api/public/hooks/mark-overdue': typeof ApiPublicHooksMarkOverdueRoute
  '/api/public/wechat/callback': typeof ApiPublicWechatCallbackRoute
  '/admin/shop/orders/': typeof AdminShopOrdersIndexRoute
  '/admin/shop/products/': typeof AdminShopProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/products'
    | '/shipping'
    | '/sitemap.xml'
    | '/track'
    | '/account'
    | '/checkout'
    | '/invoices'
    | '/admin/cargo-types'
    | '/admin/destinations'
    | '/admin/detained'
    | '/admin/forbidden'
    | '/admin/history'
    | '/admin/hs-codes'
    | '/admin/intake-scan'
    | '/admin/logs'
    | '/admin/measure'
    | '/admin/messages'
    | '/admin/oversize-rules'
    | '/admin/routes'
    | '/admin/system'
    | '/admin/tracking-presets'
    | '/admin/warehouses'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
    | '/forwarding/$forwardingId'
    | '/orders/$orderId'
    | '/pay/$orderId'
    | '/admin/batches/$batchId'
    | '/admin/cartons/$cartonId'
    | '/admin/delivery-queue/$customerKey'
    | '/admin/forwardings/$forwardingId'
    | '/admin/invoices/$invoiceId'
    | '/admin/orders/$orderId'
    | '/admin/orders/procurement'
    | '/admin/pallets/$palletId'
    | '/admin/receivings/$receivingId'
    | '/admin/shop/articles'
    | '/admin/shop/banners'
    | '/admin/shop/categories'
    | '/admin/shop/coupons'
    | '/admin/shop/inventory'
    | '/admin/users/$userId'
    | '/admin/waybills/$waybillId'
    | '/forwarding/'
    | '/admin/batches/'
    | '/admin/cartons/'
    | '/admin/delivery-queue/'
    | '/admin/forwardings/'
    | '/admin/invoices/'
    | '/admin/orders/'
    | '/admin/pallets/'
    | '/admin/receivings/'
    | '/admin/shop/'
    | '/admin/users/'
    | '/admin/waybills/'
    | '/admin/shop/orders/$orderId'
    | '/admin/shop/orders/procurement'
    | '/admin/shop/products/$productId'
    | '/api/public/hooks/mark-overdue'
    | '/api/public/wechat/callback'
    | '/admin/shop/orders/'
    | '/admin/shop/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/shipping'
    | '/sitemap.xml'
    | '/track'
    | '/account'
    | '/checkout'
    | '/invoices'
    | '/admin/cargo-types'
    | '/admin/destinations'
    | '/admin/detained'
    | '/admin/forbidden'
    | '/admin/history'
    | '/admin/hs-codes'
    | '/admin/intake-scan'
    | '/admin/logs'
    | '/admin/measure'
    | '/admin/messages'
    | '/admin/oversize-rules'
    | '/admin/routes'
    | '/admin/system'
    | '/admin/tracking-presets'
    | '/admin/warehouses'
    | '/products/$slug'
    | '/admin'
    | '/products'
    | '/forwarding/$forwardingId'
    | '/orders/$orderId'
    | '/pay/$orderId'
    | '/admin/batches/$batchId'
    | '/admin/cartons/$cartonId'
    | '/admin/delivery-queue/$customerKey'
    | '/admin/forwardings/$forwardingId'
    | '/admin/invoices/$invoiceId'
    | '/admin/orders/$orderId'
    | '/admin/orders/procurement'
    | '/admin/pallets/$palletId'
    | '/admin/receivings/$receivingId'
    | '/admin/shop/articles'
    | '/admin/shop/banners'
    | '/admin/shop/categories'
    | '/admin/shop/coupons'
    | '/admin/shop/inventory'
    | '/admin/users/$userId'
    | '/admin/waybills/$waybillId'
    | '/forwarding'
    | '/admin/batches'
    | '/admin/cartons'
    | '/admin/delivery-queue'
    | '/admin/forwardings'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/pallets'
    | '/admin/receivings'
    | '/admin/shop'
    | '/admin/users'
    | '/admin/waybills'
    | '/admin/shop/orders/$orderId'
    | '/admin/shop/orders/procurement'
    | '/admin/shop/products/$productId'
    | '/api/public/hooks/mark-overdue'
    | '/api/public/wechat/callback'
    | '/admin/shop/orders'
    | '/admin/shop/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/products'
    | '/shipping'
    | '/sitemap.xml'
    | '/track'
    | '/_authenticated/account'
    | '/_authenticated/checkout'
    | '/_authenticated/invoices'
    | '/admin/cargo-types'
    | '/admin/destinations'
    | '/admin/detained'
    | '/admin/forbidden'
    | '/admin/history'
    | '/admin/hs-codes'
    | '/admin/intake-scan'
    | '/admin/logs'
    | '/admin/measure'
    | '/admin/messages'
    | '/admin/oversize-rules'
    | '/admin/routes'
    | '/admin/system'
    | '/admin/tracking-presets'
    | '/admin/warehouses'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
    | '/_authenticated/forwarding/$forwardingId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/pay/$orderId'
    | '/admin/batches/$batchId'
    | '/admin/cartons/$cartonId'
    | '/admin/delivery-queue/$customerKey'
    | '/admin/forwardings/$forwardingId'
    | '/admin/invoices/$invoiceId'
    | '/admin/orders/$orderId'
    | '/admin/orders/procurement'
    | '/admin/pallets/$palletId'
    | '/admin/receivings/$receivingId'
    | '/admin/shop/articles'
    | '/admin/shop/banners'
    | '/admin/shop/categories'
    | '/admin/shop/coupons'
    | '/admin/shop/inventory'
    | '/admin/users/$userId'
    | '/admin/waybills/$waybillId'
    | '/_authenticated/forwarding/'
    | '/admin/batches/'
    | '/admin/cartons/'
    | '/admin/delivery-queue/'
    | '/admin/forwardings/'
    | '/admin/invoices/'
    | '/admin/orders/'
    | '/admin/pallets/'
    | '/admin/receivings/'
    | '/admin/shop/'
    | '/admin/users/'
    | '/admin/waybills/'
    | '/admin/shop/orders/$orderId'
    | '/admin/shop/orders/procurement'
    | '/admin/shop/products/$productId'
    | '/api/public/hooks/mark-overdue'
    | '/api/public/wechat/callback'
    | '/admin/shop/orders/'
    | '/admin/shop/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  ApiPublicHooksMarkOverdueRoute: typeof ApiPublicHooksMarkOverdueRoute
  ApiPublicWechatCallbackRoute: typeof ApiPublicWechatCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/warehouses': {
      id: '/admin/warehouses'
      path: '/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AdminWarehousesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tracking-presets': {
      id: '/admin/tracking-presets'
      path: '/tracking-presets'
      fullPath: '/admin/tracking-presets'
      preLoaderRoute: typeof AdminTrackingPresetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/oversize-rules': {
      id: '/admin/oversize-rules'
      path: '/oversize-rules'
      fullPath: '/admin/oversize-rules'
      preLoaderRoute: typeof AdminOversizeRulesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/measure': {
      id: '/admin/measure'
      path: '/measure'
      fullPath: '/admin/measure'
      preLoaderRoute: typeof AdminMeasureRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intake-scan': {
      id: '/admin/intake-scan'
      path: '/intake-scan'
      fullPath: '/admin/intake-scan'
      preLoaderRoute: typeof AdminIntakeScanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hs-codes': {
      id: '/admin/hs-codes'
      path: '/hs-codes'
      fullPath: '/admin/hs-codes'
      preLoaderRoute: typeof AdminHsCodesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forbidden': {
      id: '/admin/forbidden'
      path: '/forbidden'
      fullPath: '/admin/forbidden'
      preLoaderRoute: typeof AdminForbiddenRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/detained': {
      id: '/admin/detained'
      path: '/detained'
      fullPath: '/admin/detained'
      preLoaderRoute: typeof AdminDetainedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cargo-types': {
      id: '/admin/cargo-types'
      path: '/cargo-types'
      fullPath: '/admin/cargo-types'
      preLoaderRoute: typeof AdminCargoTypesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/waybills/': {
      id: '/admin/waybills/'
      path: '/waybills'
      fullPath: '/admin/waybills/'
      preLoaderRoute: typeof AdminWaybillsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/': {
      id: '/admin/shop/'
      path: '/shop'
      fullPath: '/admin/shop/'
      preLoaderRoute: typeof AdminShopIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/receivings/': {
      id: '/admin/receivings/'
      path: '/receivings'
      fullPath: '/admin/receivings/'
      preLoaderRoute: typeof AdminReceivingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pallets/': {
      id: '/admin/pallets/'
      path: '/pallets'
      fullPath: '/admin/pallets/'
      preLoaderRoute: typeof AdminPalletsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forwardings/': {
      id: '/admin/forwardings/'
      path: '/forwardings'
      fullPath: '/admin/forwardings/'
      preLoaderRoute: typeof AdminForwardingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/delivery-queue/': {
      id: '/admin/delivery-queue/'
      path: '/delivery-queue'
      fullPath: '/admin/delivery-queue/'
      preLoaderRoute: typeof AdminDeliveryQueueIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cartons/': {
      id: '/admin/cartons/'
      path: '/cartons'
      fullPath: '/admin/cartons/'
      preLoaderRoute: typeof AdminCartonsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/batches/': {
      id: '/admin/batches/'
      path: '/batches'
      fullPath: '/admin/batches/'
      preLoaderRoute: typeof AdminBatchesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/forwarding/': {
      id: '/_authenticated/forwarding/'
      path: '/forwarding'
      fullPath: '/forwarding/'
      preLoaderRoute: typeof AuthenticatedForwardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/waybills/$waybillId': {
      id: '/admin/waybills/$waybillId'
      path: '/waybills/$waybillId'
      fullPath: '/admin/waybills/$waybillId'
      preLoaderRoute: typeof AdminWaybillsWaybillIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/inventory': {
      id: '/admin/shop/inventory'
      path: '/shop/inventory'
      fullPath: '/admin/shop/inventory'
      preLoaderRoute: typeof AdminShopInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/coupons': {
      id: '/admin/shop/coupons'
      path: '/shop/coupons'
      fullPath: '/admin/shop/coupons'
      preLoaderRoute: typeof AdminShopCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/categories': {
      id: '/admin/shop/categories'
      path: '/shop/categories'
      fullPath: '/admin/shop/categories'
      preLoaderRoute: typeof AdminShopCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/banners': {
      id: '/admin/shop/banners'
      path: '/shop/banners'
      fullPath: '/admin/shop/banners'
      preLoaderRoute: typeof AdminShopBannersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/articles': {
      id: '/admin/shop/articles'
      path: '/shop/articles'
      fullPath: '/admin/shop/articles'
      preLoaderRoute: typeof AdminShopArticlesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/receivings/$receivingId': {
      id: '/admin/receivings/$receivingId'
      path: '/receivings/$receivingId'
      fullPath: '/admin/receivings/$receivingId'
      preLoaderRoute: typeof AdminReceivingsReceivingIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pallets/$palletId': {
      id: '/admin/pallets/$palletId'
      path: '/pallets/$palletId'
      fullPath: '/admin/pallets/$palletId'
      preLoaderRoute: typeof AdminPalletsPalletIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/procurement': {
      id: '/admin/orders/procurement'
      path: '/orders/procurement'
      fullPath: '/admin/orders/procurement'
      preLoaderRoute: typeof AdminOrdersProcurementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices/$invoiceId': {
      id: '/admin/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forwardings/$forwardingId': {
      id: '/admin/forwardings/$forwardingId'
      path: '/forwardings/$forwardingId'
      fullPath: '/admin/forwardings/$forwardingId'
      preLoaderRoute: typeof AdminForwardingsForwardingIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/delivery-queue/$customerKey': {
      id: '/admin/delivery-queue/$customerKey'
      path: '/delivery-queue/$customerKey'
      fullPath: '/admin/delivery-queue/$customerKey'
      preLoaderRoute: typeof AdminDeliveryQueueCustomerKeyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cartons/$cartonId': {
      id: '/admin/cartons/$cartonId'
      path: '/cartons/$cartonId'
      fullPath: '/admin/cartons/$cartonId'
      preLoaderRoute: typeof AdminCartonsCartonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/batches/$batchId': {
      id: '/admin/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/admin/batches/$batchId'
      preLoaderRoute: typeof AdminBatchesBatchIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/pay/$orderId': {
      id: '/_authenticated/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof AuthenticatedPayOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forwarding/$forwardingId': {
      id: '/_authenticated/forwarding/$forwardingId'
      path: '/forwarding/$forwardingId'
      fullPath: '/forwarding/$forwardingId'
      preLoaderRoute: typeof AuthenticatedForwardingForwardingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/shop/products/': {
      id: '/admin/shop/products/'
      path: '/shop/products'
      fullPath: '/admin/shop/products/'
      preLoaderRoute: typeof AdminShopProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/orders/': {
      id: '/admin/shop/orders/'
      path: '/shop/orders'
      fullPath: '/admin/shop/orders/'
      preLoaderRoute: typeof AdminShopOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/wechat/callback': {
      id: '/api/public/wechat/callback'
      path: '/api/public/wechat/callback'
      fullPath: '/api/public/wechat/callback'
      preLoaderRoute: typeof ApiPublicWechatCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mark-overdue': {
      id: '/api/public/hooks/mark-overdue'
      path: '/api/public/hooks/mark-overdue'
      fullPath: '/api/public/hooks/mark-overdue'
      preLoaderRoute: typeof ApiPublicHooksMarkOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shop/products/$productId': {
      id: '/admin/shop/products/$productId'
      path: '/shop/products/$productId'
      fullPath: '/admin/shop/products/$productId'
      preLoaderRoute: typeof AdminShopProductsProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/orders/procurement': {
      id: '/admin/shop/orders/procurement'
      path: '/shop/orders/procurement'
      fullPath: '/admin/shop/orders/procurement'
      preLoaderRoute: typeof AdminShopOrdersProcurementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/orders/$orderId': {
      id: '/admin/shop/orders/$orderId'
      path: '/shop/orders/$orderId'
      fullPath: '/admin/shop/orders/$orderId'
      preLoaderRoute: typeof AdminShopOrdersOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedForwardingForwardingIdRoute: typeof AuthenticatedForwardingForwardingIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedPayOrderIdRoute: typeof AuthenticatedPayOrderIdRoute
  AuthenticatedForwardingIndexRoute: typeof AuthenticatedForwardingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedForwardingForwardingIdRoute:
    AuthenticatedForwardingForwardingIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedPayOrderIdRoute: AuthenticatedPayOrderIdRoute,
  AuthenticatedForwardingIndexRoute: AuthenticatedForwardingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCargoTypesRoute: typeof AdminCargoTypesRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminDetainedRoute: typeof AdminDetainedRoute
  AdminForbiddenRoute: typeof AdminForbiddenRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminHsCodesRoute: typeof AdminHsCodesRoute
  AdminIntakeScanRoute: typeof AdminIntakeScanRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMeasureRoute: typeof AdminMeasureRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOversizeRulesRoute: typeof AdminOversizeRulesRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTrackingPresetsRoute: typeof AdminTrackingPresetsRoute
  AdminWarehousesRoute: typeof AdminWarehousesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBatchesBatchIdRoute: typeof AdminBatchesBatchIdRoute
  AdminCartonsCartonIdRoute: typeof AdminCartonsCartonIdRoute
  AdminDeliveryQueueCustomerKeyRoute: typeof AdminDeliveryQueueCustomerKeyRoute
  AdminForwardingsForwardingIdRoute: typeof AdminForwardingsForwardingIdRoute
  AdminInvoicesInvoiceIdRoute: typeof AdminInvoicesInvoiceIdRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersProcurementRoute: typeof AdminOrdersProcurementRoute
  AdminPalletsPalletIdRoute: typeof AdminPalletsPalletIdRoute
  AdminReceivingsReceivingIdRoute: typeof AdminReceivingsReceivingIdRoute
  AdminShopArticlesRoute: typeof AdminShopArticlesRoute
  AdminShopBannersRoute: typeof AdminShopBannersRoute
  AdminShopCategoriesRoute: typeof AdminShopCategoriesRoute
  AdminShopCouponsRoute: typeof AdminShopCouponsRoute
  AdminShopInventoryRoute: typeof AdminShopInventoryRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminWaybillsWaybillIdRoute: typeof AdminWaybillsWaybillIdRoute
  AdminBatchesIndexRoute: typeof AdminBatchesIndexRoute
  AdminCartonsIndexRoute: typeof AdminCartonsIndexRoute
  AdminDeliveryQueueIndexRoute: typeof AdminDeliveryQueueIndexRoute
  AdminForwardingsIndexRoute: typeof AdminForwardingsIndexRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPalletsIndexRoute: typeof AdminPalletsIndexRoute
  AdminReceivingsIndexRoute: typeof AdminReceivingsIndexRoute
  AdminShopIndexRoute: typeof AdminShopIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWaybillsIndexRoute: typeof AdminWaybillsIndexRoute
  AdminShopOrdersOrderIdRoute: typeof AdminShopOrdersOrderIdRoute
  AdminShopOrdersProcurementRoute: typeof AdminShopOrdersProcurementRoute
  AdminShopProductsProductIdRoute: typeof AdminShopProductsProductIdRoute
  AdminShopOrdersIndexRoute: typeof AdminShopOrdersIndexRoute
  AdminShopProductsIndexRoute: typeof AdminShopProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCargoTypesRoute: AdminCargoTypesRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminDetainedRoute: AdminDetainedRoute,
  AdminForbiddenRoute: AdminForbiddenRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminHsCodesRoute: AdminHsCodesRoute,
  AdminIntakeScanRoute: AdminIntakeScanRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMeasureRoute: AdminMeasureRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOversizeRulesRoute: AdminOversizeRulesRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTrackingPresetsRoute: AdminTrackingPresetsRoute,
  AdminWarehousesRoute: AdminWarehousesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBatchesBatchIdRoute: AdminBatchesBatchIdRoute,
  AdminCartonsCartonIdRoute: AdminCartonsCartonIdRoute,
  AdminDeliveryQueueCustomerKeyRoute: AdminDeliveryQueueCustomerKeyRoute,
  AdminForwardingsForwardingIdRoute: AdminForwardingsForwardingIdRoute,
  AdminInvoicesInvoiceIdRoute: AdminInvoicesInvoiceIdRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersProcurementRoute: AdminOrdersProcurementRoute,
  AdminPalletsPalletIdRoute: AdminPalletsPalletIdRoute,
  AdminReceivingsReceivingIdRoute: AdminReceivingsReceivingIdRoute,
  AdminShopArticlesRoute: AdminShopArticlesRoute,
  AdminShopBannersRoute: AdminShopBannersRoute,
  AdminShopCategoriesRoute: AdminShopCategoriesRoute,
  AdminShopCouponsRoute: AdminShopCouponsRoute,
  AdminShopInventoryRoute: AdminShopInventoryRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminWaybillsWaybillIdRoute: AdminWaybillsWaybillIdRoute,
  AdminBatchesIndexRoute: AdminBatchesIndexRoute,
  AdminCartonsIndexRoute: AdminCartonsIndexRoute,
  AdminDeliveryQueueIndexRoute: AdminDeliveryQueueIndexRoute,
  AdminForwardingsIndexRoute: AdminForwardingsIndexRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPalletsIndexRoute: AdminPalletsIndexRoute,
  AdminReceivingsIndexRoute: AdminReceivingsIndexRoute,
  AdminShopIndexRoute: AdminShopIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWaybillsIndexRoute: AdminWaybillsIndexRoute,
  AdminShopOrdersOrderIdRoute: AdminShopOrdersOrderIdRoute,
  AdminShopOrdersProcurementRoute: AdminShopOrdersProcurementRoute,
  AdminShopProductsProductIdRoute: AdminShopProductsProductIdRoute,
  AdminShopOrdersIndexRoute: AdminShopOrdersIndexRoute,
  AdminShopProductsIndexRoute: AdminShopProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  ApiPublicHooksMarkOverdueRoute: ApiPublicHooksMarkOverdueRoute,
  ApiPublicWechatCallbackRoute: ApiPublicWechatCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
